### ISSUE TITLE
Unknown Firewall (a8ddfccd5)

### ISSUE THREAD

**Issue by WhatWaf-Firewalls** [Ekultek/WhatWaf#555] opened 2019-11-06 12:32 UTC
WhatWaf version: `1.6.11`
Running context: `whatwaf.py -u ****************************************`
Fingerprint:
```
<!--
GET http://challenge-status.fblcloud-qa.net HTTP/1.1
Status code: 403
Date: Wed, 06 Nov 2019 12:31:49 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: SPSI=669856d294536f22ecd4c2c9db5267e9; Path=/, spcsrf=a5de7e1dd4ca01ca9b654813182c18b6; Expires=Wed, 06-Nov-19 14:31:49 GMT; Path=/; HttpOnly; SameSite=Strict
server: fbs
cache-control: no-store, no-cache, max-age=0, must-revalidate, private,  max-stale=0, post-check=0, pre-check=0
X-Accel-Expires: 0
Surrogate-Control: no-store
Content-Encoding: gzip
-->
<!DOCTYPE html>
 <html lang="en"> <head> <title>Sorry, you have been blocked</title> <meta charset="utf-8"/> <meta content="width=device-width, initial-scale=1" name="viewport"/> <meta content="NO-CACHE" http-equiv="CACHE-CONTROL"> <meta content="noindex, nofollow" name="robots"/> <style type="text/css"> html{height: 100%}body{margin: 0;height: 100%;}header{background-color: #020202;height: 64px;width: 100%;}header img{margin: 3px 0 0 2px;}section{height: calc(100% - 64px);}.content{padding: 0;position: relative;top: calc(50% - 64px);text-align: center;margin: auto;transform: translateY(-50%);}.left-img{display: inline-block;margin: 0 17px 0 0;}.right-msg{display: inline-block;color: #4b4b4b;vertical-align: top;text-align: left;}.msg-head{margin: 0;font-size: 35px;line-height: 33px;font-weight: bold;font-family: 'Arial Narrow', Arial, sans-serif;}.msg-main{margin-top: 14px;padding: 0 0 0 6px;font-size: 13px;line-height: 16px;font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;}.icon{margin: 12px 9px 0 2px;}.incident-id{margin-top: 16px;display: inline-block;font-size: 15px;vertical-align: top;font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;}@media(max-width: 768px){header img{margin-top: 3px;min-width: 400px;width: 100%;max-width: 561px;height: 65px;}.content{top: 200px;}}@media(max-width: 652px){.left-img{display: none;}.content{top: 200px;padding: 0 10px;}}@media(max-height: 580px){.content{top: 200px;}}</style> </meta></head> <body> <header> </header> <section> <div class="content"> <div class="left-img"> <img alt="STOP" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAK8AAACDCAYAAAD7/Es4AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACNFJREFUeNrsnU9sFFUcx9/WCvKv1r8xSNJyIcCFnpQb20g4eOlCOHABWg5c0LRNOIgHCx7EA4klwoWDXcLFA5Hl4sGIXRIOxos9geFCm2CiKFpKiAJCfd/Zt6HW3XlvZndn3p/vJ5lM03Y3M28+85vf+703M4XFxUVBiK0UCgWsBpf8arrubDebhzjAoaXy1n/oYrsQV6G8hPISQnkJobyE8hJCeQmhvIRQXkJ5CaG8hFBeQnkJobyEUF5CKC+hvIRQXkIoLwkHa+9hUzfe5c5c36aiXA3IZZtc+tXPvZqPzaplBl+Bdd/czaotbevLTbcFW3ckL3mlrJCzJJcdcim2+eshMyS+nKfMLsmrPLiw5Ff769tPeWvC9ithR1V0zYJ5uVTkcj5rkSmvB/KqlOCgXIZz3l2kGKflUpYiz1NeyquTdqIDaUE7ojEknuykxL7IG1S1AemBXC6J2oMrihZuYq86qW7J7TzOekI8XQGJCxl+VLmt7UQSy22+pa4SpAHdAUiLDhii7UCr37Vi6xbx3IY3o3VXz7po3YhH12+Ipwv3o/WT2z9H65Rg26flPqBjN5JFPuwSXue88qCjI/aZ0Ndlm8q6cvtbYvWundE6LU8XFsTD738Qf8vlr2++Ff9IoVPmw7vbUZlgh81yeaW4U2mqCN0ysq47dFCsksLi506ASHz/i/NS5CuR2Ak5IQU+Tnk9lFdK26vShES54gsysr449n5LETZNRH5w8VIkcsJoXJbLeNo0gvJaKK8SdzpJfpuHtI24N3kmkjhBJMZo3WAagSmvZfImFRcpwSunPs1d2uWR+O7RY1Fe3EmBWee1q6KQSFxE2vXXvrNK3Ohg9PSI186djRb8bMCAqkb0igDpCklcRNs3vq5Ied+zep/QWVx/7UqU0lBgj+WVTJmICyEgbrParHUHRkbe17+8INbs3W0q8BTldSvqooarHTGDAAkuxVaBvByLASXVHpTXAXEh7VgbD7614OQz3Icx1S6U12Jx+00ukzjghpddnwSeCiX/dTXyQtzYA/TSRx96I+5SgTH6p6E+SEN5LYy6w0IzemZ4kJ3E8KQsqnbyGqcGKdTl8FZc1EV5Cb10n8Fgxp19B3Sz1TBwsbHRAAYHKfJhIk5cVBNePXfW/8ul3M+XT500SR8mmDbY00kbi++gnXSyHJYG1KsxUmhQfeinvHZE3dg8FwMRIYGRQoNBlwnKm3/UHY67jKIjEyIG+z3sa/R1JfKO6iJQKOnCcjC5yKD6MEx584m6vXGNX7/zIWQMct9RypsPpbgKg8GB8x6cwJro2+tj3dcFeQ/G5bqrdr0jiBBr9+7R/csQ5c0+ZSjGVRhCzXUb5b6aykPJtzkPtkfe2BlSvs1daBWD3L9IebNjKC7Pc2VieVYYpFBDlDc7is0P1E7a2qAPoLl1iJE3o3w39gnkqylvmpO636cBC5sj74Cug0JStcsA5e08TSMEc93mGLQN5c2AHc3+8PzWzbQ0Bk3eu82X/bT5Eae9zSsNG7QfxjPAUj6N0e4Dph9Nkyf3luiJlEnblfJmkPOuMIi8Dy5+FXcAnY6qOnk1AzdMG3LdaI6qafLezamuaJSX8OSmvIRQXkJ5CaG8hIQrr4/123aS4iUtlJfy2sGj6z8FsZ82D1LgfQsDjeW9rf3wmr17xMrtb/t3wAxer6WJvFXK23maviTksUFkCfkui8fp37jJtKFNXG1+WbwhSHM0w+JXKW/nmY3740MP5y20J9/VntjzlDebnDdtdAkWg5N6hvJ2mL65mzNxUSLBi/aYMvy3XauUNxuqcZdHlsz+X2XQnNRVn/bXdnkvx/2R0Xd5e1xJ3QmmvO2nEvdHvGiaPAMT8FtpT8rb3rx3Pq7BkTaw6vAsjdLku7OqH0F5bUkd7k1+TnPNrkLeXaZckLcSV3VAtAk9+uIKhBtONZQpbz6pQ5nRt6X9L8t2nKW8+XA67o8hR1/st0HUPeHjvjshr4oasdH37tEPgpT3z48/0aZdPkZdlyKvNnog77s3eSa4TprBXIZxX/ffGXlV9JjU5X6hzDjDfhpE3bKvUde1yFuPvrGzon4/fMT722Cwf38cPab7t3mfo65z8qrKw7gufYDAPnNXimuSLjR6aTblzVdgdNyquuqDrx047JfBnI6KaidBee1jty59QPnIt7kPENegLIZ2GQkh73dSXnU51B4gdGgMDrZP4kYntu/pguuRFwJXhEHxHQfdoFfui7jjPk0291ZeJfBxYTBmj/TBxRwYVYU7+/abiouy2KQICB8e94Tqg3aqHwT45d2SM3dfoJqA7TW8V68qxR0RgeG8vCq/GzQRuC6E7XdgYKQwwYk2ozqwgvJ6LjAuxb8dPhIttkVhTLKBtAlmyWF/B0PpoHkpb1KBAaJvTZQzuY/I4STCyfSrzG8TDG+XQxYXFBYXF+3csEIh9Wfn+jZNydWw8Rnc0xO9dHrdoQOZPhIfkXZBdiZTpDHlVnJcW495jAcXlvxqf337vZRXCYxKxETSz+EZZ2ujh/R15g2biLKQFRWQlGnLSKujZ5TXcnmVwEW5Qp0p8Rtw8DRGCIx3HGPdSkRGhEXVANK2MOttVtQGIFq+iZLyOiCvEhjiIo0otfI9kLkmdO2xqc3eMlkvbUHSJzKytmmKJuq3J9qV31JeR+RdInFJSezSe8hmVZpQbeeX+iJvMO+kUMPJG4Ub93PNq0i7MaTh3qQE9UIVXHbVkDIkLtsqLbZPbSeJi8qhpA1NUol+USupjeacTiA9wPzNySzqtsx5PZB3mciQeKjVjl1CkMqcVylNZlBez+RdVp0oKZGLbY7IiLDIYfG0xkpeo2OU11N5G8iMNxJhQYqxQ8k8YPDRekcLoqI2O2PLnby+yGvt24AsauAZ0aZH4bujDKsNhFBeQigvobyEUF5CKC+hvIRQXkIoLyGUl1BeQigvIZSXUF5CKC8hlJcQyksoLyGUlxDKS8Kmm01AHGC60S8LLt0GTcKj0SMQ6s7+K8AAYrvl2HnOm/MAAAAASUVORK5CYII="/> </div> <div class="right-msg"> <h1 class="msg-head">Sorry, you have been blocked</h1> <p class="msg-main"> This website is using a security service to protect itself from online attacks.<br/> You performed an action that triggered the service and blocked your request. </p> <img alt="Incident" class="icon" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAB0AAAAaCAYAAABLlle3AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABSBJREFUeNrkVltPY1UY/VpaaMu1kFAiw6Wl3Nva0mHoTEAGhsgwCSTERIwTJ4Y3n3zwB/ADzPg8Og9GzBhJxmBICI4iNShyKVIuQoGWW4FyGSiFMlCgBdfetgQYCzzpgydpetpzzl7fWutb3z6Ck5MT+rcPIf0Hh+jsj4qKytPzo6MjEolEdHx8TEKhkH+gSrzf7087ODi4he97YrHYGBUVlS4URjQKhYJvLy4eUtFs7goPevEQCATsS40Cbh0eHhpRgFYmkxkzM5WJhYUFpNEUUmdnJw0NDX8MiGxcjzz7rEQiQd2iafz88ipQGSrMB5Myn2+/FAw1cnmiKiMjQ6zXv0l6vZ6USiUpFClgL6BXr/ZoeHjEdPNmsQmsg8oIKBA4oZkZB21ubvZeCorqPgWr2wAtUKmUcq1WS7m5uWCkodTUVIqOjn6twry8XPwfQ48efUA6nY5LygTy+Q6pqamJ5ufn9y71dH9//yOTyRTd0PAuxcbGUFSUhNRq9aVNkZ+fT3FxcTQ2NkbFxcVnCAhDvp5c2r3w7afkZAUBGLK46cmTz2lxcTEsIJOSsddqNTQ4+AckDZxeY+fh4ngOFKa3Dw9baWNjA93rp6SkJBoYsLBiTu/xer00OjpGLS0t9PjxZ+RwzFBZWSn8m0GByxzoquyfkzcyMrLf5XJt2e0OeWZmBuQyQnIfLS8v09zcHAfY2dkhmSya2HVmQ0pKCkmlEoqIiKCnT7/gdshkUqqpqeH/XQmK3C14PB7r+Ph4pU73HnV1ddHCwiL5/YeUmJjIG4XFRCKRopAlmp2dQ1yGqLy8nNDd5PFsgXUZW4cDnpX7ssjsQOJ+q3Wosrr6bf7w3bvllJOTzc8nJmz04sWPtLq6yoeHXJ6A7s2n+Ph4MhiKkFl2bYUSEhJwTR7K+eWgzAssPgB5fVhUUlVVRf39/dTc/DVYeNA0MsrOzqaiIgPFxMTwj9PppOnpaW5Fc/NXAP6Z7ty5Tenp6dcDDUo8CgAnJM5h/jF2BoMebHN4Ubu7Xt4wvb19tL6+zp8pL3+LsrJUyPIbGBrJuN/A5Q3XUK+B4mYnvBixWCw5tbW1nBmbLMxfl2sVjbXHu1qtzqIHD2q4lCxWLJdGo5FaW1uR8Viqq6vjk+lKUCYHqvNjnP06NTX9DpgIzeZfuE8MnDG6cSOVe2i326m7uxuN5uQN8/Dh+3xEdnT8wHMeGonX8jQYnd9crpVteCW/f78a3evnBc3OzlJbWxutra3xRVUqFWfLimAdzdhjyPNma2z88HQqXSlv8JjE9vXn+PhEmVaro+fPv+P5TE5OxtjLo/r6egwSMTxdQ3Rc1NPzO98GWW41mgKy2Wz8+rU9Dcq8D2J9o6OjZSw6paWlPDa8mslJ+GvmA4NNqpQUBaRXg3UWbFgDkIBWVlZoe3v7esPhwkjscTjsnwQCx8K4uFh69uwbHn62o6SlpVNlZQWX1evdAbNJam9vR3TsPL/MW5TOs/1PbMOCospBt3trYWrKpmQDgA11hUKBjoygpaVFvA2YyWod5uPR7XbzYWAylVBJSQkviv3/8uU68z7q2qDYvFdR5QD8UjLpWCxaW78n5Jc10iqkDYCJgHnJdhqxWEQjIyNksQzyxvt7BJ5Apbj1a3Vv0NcAJo65r6+/AQvtYWDYsJCVxQlgNqlU6sf9gtAzXu/uaZeHJhHui8Cp58qcXmA7BEbtADMDpAOST7FiQnvlhSL5y1u40XcO53/z3vuXAAMAGHpywSLn9WUAAAAASUVORK5CYII="/> <div class="incident-id">Reference ID: 7eacbce36e00113afe985bc94572d9a7</div> </div> </div> </section> </body> </html>
```

**Comment by Ekultek** [comment] 2019-12-01 23:11
please email me the actual URL

**Comment by Ekultek** [comment] 2019-12-01 23:18
dupe of #516

**Closed by Ekultek** 2019-12-01 23:18 UTC
Labels: Research Needed
