### ISSUE TITLE
Whatwaf Unhandled Exception (8244aeb74)

### ISSUE THREAD

**Issue by WhatWaf-Firewalls** [Ekultek/WhatWaf#267] opened 2019-06-06 15:03 UTC
Whatwaf version: `1.4.5`
Running context: `./whatwaf.py -u *************************** --ra --verbose`
Traceback: 
```
Traceback (most recent call):
  File "/Users/popolun/virtualenv_test/WhatWaf/whatwaf/main.py", line 444, in main
    save_copy_of_file=opt.outputDirectory
  File "/Users/popolun/virtualenv_test/WhatWaf/content/__init__.py", line 735, in detection_main
    timeout=req_timeout
  File "/Users/popolun/virtualenv_test/WhatWaf/content/__init__.py", line 374, in get_working_tampers
    throttle=throttle, timeout=req_timeout
'NoneType' object is not iterable
```
Running platform: `Darwin-18.2.0-x86_64-i386-64bit`

**Comment by Ekultek** [comment] 2019-06-08 02:19
dupe of #229

**Closed by Ekultek** 2019-06-08 02:19 UTC
