### ISSUE TITLE
Unknown Firewall (9c47d0192)

### ISSUE THREAD

**Issue by WhatWaf-Firewalls** [Ekultek/WhatWaf#213] opened 2019-02-18 17:55 UTC
WhatWaf version: `1.2.1`
Running context: `<closed file '/root/.whatwaf/fingerprints/www.104.254.204.248', mode 'r' at 0x7f26e47e0300>`
Fingerprint:
```
<!--
GET http://104.254.204.248 HTTP/1.1
Status code: 403
Cache-Control: no-cache
Connection: close
Content-Type: text/html
-->
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

```

**Comment by Ekultek** [comment] 2019-02-18 22:48
dupe of #212

**Closed by Ekultek** 2019-02-18 22:48 UTC
