### ISSUE TITLE
Whatwaf Unhandled Exception (5512b8b31)

### ISSUE THREAD

**Issue by WhatWaf-Firewalls** [Ekultek/WhatWaf#229] opened 2019-03-02 21:46 UTC
Whatwaf version: `1.2.6`
Running context: `./whatwaf.py -u ************************************************ -p AND 7549=(SELECT (CASE WHEN (7549=7549) THEN 7549 ELSE (SELECT 3817 UNION SELECT 8658) END))-- LYUE --proxy ***********************`
Traceback: 
```
Traceback (most recent call):
  File "/home/sphinx/Apps/WhatWaf/whatwaf/main.py", line 363, in main
    save_copy_of_file=opt.outputDirectory
  File "/home/sphinx/Apps/WhatWaf/content/__init__.py", line 514, in detection_main
    _, status, html, headers = item
'NoneType' object is not iterable
```
Running platform: `Linux-4.8.0-53-generic-x86_64-with-LinuxMint-18.2-sonya`

**Comment by Ekultek** [comment] 2019-03-04 14:22
i cannot reproduce this, would you be willing to send me the URL via email?

**Comment by Ekultek** [comment] 2019-07-15 19:13
fixed via https://github.com/Ekultek/WhatWaf/commit/2a55052d055e06a278ea1de0b56fe16a48786912

**Closed by Ekultek** 2019-07-15 19:13 UTC
Labels: bug
