### ISSUE TITLE
[FATAL] WhatWaf has caught an unhandled exception with the error message: 'Unicode-objects must be encoded before hashing'.

### ISSUE THREAD

**Issue by ashok-nurture** [Ekultek/WhatWaf#92] opened 2018-07-07 17:32 UTC
------------------------------
Traceback:
```
  File "/Users/Ashok/Desktop/bahrain_dev/trials/whatwaf/whatwaf/main.py", line 210, in main
    request_type=request_type
  File "/Users/Ashok/Desktop/bahrain_dev/trials/whatwaf/content/__init__.py", line 430, in detection_main
    lib.firewall_found.request_firewall_issue_creation(path)
  File "/Users/Ashok/Desktop/bahrain_dev/trials/whatwaf/lib/firewall_found.py", line 106, in request_firewall_issue_creation
    identifier = create_identifier(data.read(chunk))
  File "/Users/Ashok/Desktop/bahrain_dev/trials/whatwaf/lib/firewall_found.py", line 25, in create_identifier
    obj.update(data)
```
CMD line: `./whatwaf.py -u ***************************`
Version: `0.8.3`
------------------------------

**Comment by Ekultek** [comment] 2018-07-07 18:04
Which version of python?

**Comment by ashok-nurture** [comment] 2018-07-07 18:05
3.6.6

**Comment by Ekultek** [comment] 2018-07-07 18:09
Okay I know what the problem is, thank you I’ll have it fixed in a couple days. For now use python 2.7

**Comment by ashok-nurture** [comment] 2018-07-07 18:11
Sure, thanks!

**Comment by Ekultek** [comment] 2018-07-07 18:11
Thank you as well!

**Comment by Ekultek** [comment] 2018-07-09 16:32
@ashok-nurture mind sending me the URL you where trying to staysalty@protonmail.com for testing purposes?

**Comment by Ekultek** [comment] 2018-07-12 15:06
@ashok-nurture ping

**Comment by ashok-nurture** [comment] 2018-07-12 16:15
@Ekultek i was simulating with below sub domain. currently i'm not able to simulate this issue.

https://finbot.nurture.co.in

**Comment by ashok-nurture** [comment] 2018-07-12 16:19
@Ekultek i think, #92 occurs when it encounters an unknown firewall and when I try to create an issue. for e.g., on google search domain..

**Comment by ashok-nurture** [comment] 2018-07-13 08:58
@Ekultek okies

**Comment by Ekultek** [comment] 2018-07-20 13:44
fixed via https://github.com/Ekultek/WhatWaf/commit/5fd9022046c28c3681d08b4ace2689eaf226ca56

**Closed by Ekultek** 2018-07-20 13:44 UTC
Labels: bug
