### ISSUE TITLE
Whatwaf Unhandled Exception (9b621d67c)

### ISSUE THREAD

**Issue by WhatWaf-Firewalls** [Ekultek/WhatWaf#244] opened 2019-04-29 06:57 UTC
Whatwaf version: `1.4.4`
Running context: `whatwaf.py -u ************** --tor`
Traceback: 
```
Traceback (most recent call):
  File "/opt/WhatWaf/whatwaf/main.py", line 322, in main
    results = test_target_connection(url_to_use, proxy=proxy, agent=agent, headers=opt.extraHeaders)
  File "/opt/WhatWaf/lib/settings.py", line 590, in test_target_connection
    _, status, _, _ = results
'NoneType' object is not iterable
```
Running platform: `Linux-4.19.0-kali4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

**Comment by Ekultek** [comment] 2019-05-10 13:44
dupe of #229

**Closed by Ekultek** 2019-05-10 13:44 UTC
Labels: bug
